name: pace_pilot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_auth_2: ^3.1.1
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0
  cached_network_image: ^3.3.1
  sqflite: ^2.3.2
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  
flutter:
  uses-material-design: true
  assets:
    - assets/icon/PacePilot.png
    - assets/images/Running_Icon.png
    - assets/images/Log_Icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/ic_launcher_round.png"